name: VLagger
main: com.mcml.space.core.VLagger
version: 2.8.2-%BUILD_NUMBER%
softdepend: [AntiAttack, Essentials, RPG Items, RPGItems]
author: Vlvxingze
authors: [IzzelAliz, Sotr]
website: "https://github.com/Vlvxingze/VLagger"
database: false

commands:
  vlg:
    description: VLagger
    usage: "/vlg help"
